### ISSUE TITLE
Register SaddleSearch

### ISSUE THREAD

**Issue by cortner** [cortner/SaddleSearch.jl#7]
I suggest that over the course of the summer we clean up SaddleSearch, i.e., we create several feature branches, then reduce the master-branch to just a few methods that work well and are tested, and the register it. How do people feel about this? (ideally I'd like to get this done before Letif finishes)

**Comment by cortner** [comment]
either nobody likes my suggestion or "watching" a repository means you don't automatically get emails about new Issues?  cc @jameskermode @molet @SMakri   :)

**Comment by SMakri** [comment]
I'm guilty, I did see this, but I left it to reply later and I forgot about it. 
It's a very good idea and perfect timing from my side (I found a bug today in the the code I wrote and it was probably there for quite a while, luckily it did not change anything qualitatively from what I've tested so far)

**Comment by cortner** [comment]
Then I guess a first decision to make is which methods to include. Which string versions work reasonably reliably?

**Comment by SMakri** [comment]
I'm certain that 'string.jl' and 'neb.jl' are reliable (these are the simple ones, 'string.jl' can be preconditioned by fixed preconditioner as well). The rest, I want to check them again, but I believe I fixed the bug I had.

**Comment by cortner** [comment]
closing for a new issue with the usual name
